// Generated by CoffeeScript 1.6.2
(function() {
  var XMLConfigParser;

  module.exports = XMLConfigParser = (function() {
    var XML2JS, parser;

    XML2JS = require('xml2js');

    parser = new XML2JS.Parser();

    function XMLConfigParser(options) {
      if (options != null) {
        this.parserOptions = {
          normalizeTags: options.normalizeTags || true,
          normalize: options.normalize || true,
          trim: options.trim || true
        };
      }
    }

    XMLConfigParser.prototype.parse = function(xml, callback) {
      parser.parseString(xml, callback);
      return xml;
    };

    return XMLConfigParser;

  })();

}).call(this);
